version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    Ccommand: --check-caps false
    ports: 
      - 1972
      - 55016:52773
      - 53773
    volumes:
      - ./:/irisdev/app
